version: '3.8'

services:
  my_xampp5:
    build: .
    container_name: myXampp5
    ports:
      - "${PORT_SSH}:22"
      - "${PORT_HTTP}:80"
      - "${PORT_HTTPS}:443"
      - "${PORT_MYSQL}:3306"
    volumes:
      - "./config:/opt/lampp/apache2/conf.d"
      - "./www:/www"
      - "mX5_db:/opt/lampp/var/mysql"
      #- "./data:/opt/lampp/var/mysql"
    networks:
      - mX5_net
    restart: always

volumes:
  mX5_db:
networks:
  mX5_net:
