version: '3.8'

services:
  my_xampp5:
    build: .
    container_name: myXampp5
    ports:
      - "${PORT_SSH}:22"
      - "${PORT_HTTP}:80"
      - "${PORT_HTTPS}:443"
      - "${PORT_MYSQL}:3306"
    volumes:
      - "./www:/www"
      - "./data:/opt/lampp/var/mysql"
    networks:
      - myxampp5
    restart: always

networks:
  myxampp5:
